spring.application.name=fleetpulseapi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

qsolutions.username=${QSOLUTIONS_USERNAME}
qsolutions.password=${QSOLUTIONS_PASSWORD}
qsolutions.proveedor=${QSOLUTIONS_PROVEEDOR}
qsolutions.tracking-number=${QSOLUTIONS_TRACKING_NUMBER}

jwt.secret=${JWT_SECRET}
jwt.access-expiry-seconds=${JWT_ACCESS_EXPIRY_SECONDS}
jwt.refresh-expiry-seconds=${JWT_REFRESH_EXPIRY_SECONDS}

gps.max-coordinate-age-seconds=${GPS_MAX_COORDINATE_AGE_SECONDS}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

app.initial-admin-username=${INITIAL_ADMIN_USERNAME}
app.initial-admin-password=${INITIAL_ADMIN_PASSWORD}